apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}-connect
  labels:
{{ include "kafka-connect.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.prometheus.jmx.enabled }}
    - name: {{ .Values.prometheus.jmx.portName }}
      port: {{ .Values.prometheus.jmx.port }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
